apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: frontend
    context: src/frontend
  - image: helloservice
    context: src/helloservice
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./k8s/**.yml
