apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: gcr.io/brymck/frontend
      context: src/frontend
    - image: gcr.io/brymck/helloservice
      context: src/helloservice
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - ./k8s/**.yaml
