apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloservice
spec:
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: gcr.io/brymck/helloservice
          ports:
            - containerPort: 3550
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  type: ClusterIP
  selector:
    app: helloservice
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550