apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: squareservice
spec:
  template:
    metadata:
      labels:
        app: squareservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/brymck/squareservice
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: squareservice
spec:
  type: ClusterIP
  selector:
    app: squareservice
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080
